import type { PhaseId } from "../types/phase.js";

export const PHASE_LABELS: Record<PhaseId, string> = {
  setup: "setup",
  implement: "implement",
  self_review: "self review",
  simplify: "simplify",
  verify: "verify",
  create_pr: "create pr",
  await_review: "awaiting review",
  route_review: "routing review",
  handle_review: "handle review",
  await_pr: "awaiting pr",
  await_merge: "awaiting merge",
  route_merge_failure: "merge failed",
  route_review_failure: "review failed",
  abort: "aborted",
  escalate: "escalate",
  cleanup: "cleanup",
  complete: "complete",
  pr_closed: "pr closed",
  run_script: "running script",
};

export const PHASE_COLORS: Record<PhaseId, string> = {
  setup: "gray",
  implement: "blue",
  self_review: "cyan",
  simplify: "cyan",
  verify: "cyan",
  create_pr: "green",
  await_review: "yellow",
  route_review: "yellow",
  handle_review: "blue",
  await_pr: "yellow",
  await_merge: "yellow",
  route_merge_failure: "red",
  route_review_failure: "red",
  abort: "red",
  escalate: "red",
  cleanup: "gray",
  complete: "green",
  pr_closed: "gray",
  run_script: "blue",
};
